""" change in bookmark table

Revision ID: 28eb9368fb4b
Revises: 6752e37e77c5
Create Date: 2024-07-24 04:33:56.295675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28eb9368fb4b'
down_revision: Union[str, None] = '6752e37e77c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('marked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmarks', 'marked_at')
    # ### end Alembic commands ###
