"""reverse change in blogs table

Revision ID: 6752e37e77c5
Revises: 2c171b8269bb
Create Date: 2024-07-23 21:05:40.906575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6752e37e77c5'
down_revision: Union[str, None] = '2c171b8269bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
