"""corrected publication table

Revision ID: e15538c1d7d5
Revises: 9e6080850aa4
Create Date: 2024-07-23 19:06:21.715309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e15538c1d7d5'
down_revision: Union[str, None] = '9e6080850aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'registered_at')
    op.create_foreign_key('fk_publication_id', 'users', 'publication', ['publication_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_publication_id', 'users', type_='foreignkey')
    op.add_column('publication', sa.Column('registered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
